In [1]:
import numpy as np

In [2]:
# Scalar Operations
# Example 1: Scalar Addition
scalar_a = 5
scalar_b = 3
scalar_addition = scalar_a +scalar_b
print("Scalar Addition:", scalar_addition)

Scalar Addition: 8


In [3]:
# Example 2: Scalar Subtraction
scalar_subtraction = scalar_a - scalar_b
print("Scalar Subtraction:", scalar_subtraction)

Scalar Subtraction: 2


In [4]:
# Example 3: Scalar Multiplication
scalar_multiplication = scalar_a * scalar_b
print("Scalar Multiplication:", scalar_multiplication)

Scalar Multiplication: 15


In [5]:
# Example 4: Scalar Division
scalar_division = scalar_a / scalar_b  # Ensure b is not zero
print("Scalar Division:", scalar_division)

Scalar Division: 1.6666666666666667


In [6]:
# Example 5: Scalar Exponentiation
scalar_exponentiation = scalar_a ** scalar_b
print("Scalar Exponentiation:", scalar_exponentiation)

Scalar Exponentiation: 125


In [7]:
# Vector Operations using NumPy
# Example 1: Vector Addition
a = np.array([3, -2, 5]) # Convert the list into NumPy array for vectorized ops
b = np.array([4, 7, -1]) # Convert the list into Numpy array for vectorized ops
vector_addition = a + b
print("Vector Addition:", vector_addition)

Vector Addition: [7 5 4]


In [8]:
# Example 2: Vector Subtraction
a = np.array([6, -3, 2]) # Convert the list into NumPy array for vectorized ops
b = np.array([1, 4, -5]) # Convert the list into NumPy array for vectorized ops
vector_subtraction = a - b
print("Vector Subtraction:", vector_subtraction)

Vector Subtraction: [ 5 -7  7]


In [9]:
# Example 3: Scalar Multiplication
scalar = 3
a = np.array([-2, 5, 4]) # Convert the list into NumPy array for vectorized ops
scalar_multiplication_vector = scalar * a
print("Scalar Multiplication with a Vector:", scalar_multiplication_vector)

Scalar Multiplication with a Vector: [-6 15 12]


In [10]:
# Example 4: Element-wise Vector Multiplication
a = np.array([2, -1, 3]) # Convert the list into NumPy array for vectorized ops
b = np.array([4, 5, -2]) # Convert the list into NumPy array for vectorized ops
elementwise_multiplication = a * b
print("Element-wise Vector Multiplication:", elementwise_multiplication)

Element-wise Vector Multiplication: [ 8 -5 -6]


In [11]:
# Example 5: Dot Product
a = np.array([1, 2, 3]) # Convert the list into NumPy array for vectorized ops
b = np.array([4, -5, 6]) # Convert the list into NumPy array for vectorized ops
dot_product = np.dot(a, b) # Compute dot product on of two vectors a & b
print("Dot Product:", dot_product)

Dot Product: 12


In [12]:
# Example 6: Cross Product
a = np.array([1, 2, 3]) # Convert the list into NumPy array for vectorized ops
b = np.array([4, 5, 6]) # Convert the list into NumPy array for vectorized ops
cross_product = np.cross(a, b) # Compute cross product of two vectors a & b
print("Cross Product:", cross_product)

Cross Product: [-3  6 -3]


In [13]:
# Example 7: Magnitude (Norm) of a Vector
a = np.array([3, 4, 5]) # Convert the list into NumPy array for vectorized ops
magnitude = np.linalg.norm(a) # Compute the magnitude/length of a vector a
print("Magnitude of Vector:", magnitude)

Magnitude of Vector: 7.0710678118654755


In [14]:
# Example 8: Unit Vector Calculation
a = np.array([3, 4, 5]) # Convert the list into NumPy array for vectorized ops
unit_vector = a / np.linalg.norm(a) # Compute the unit vector of a given the length of a vector a
print("Unit Vector:", unit_vector)

Unit Vector: [0.42426407 0.56568542 0.70710678]


In [15]:
# Example 9: Projection of One Vector onto Another
a = np.array([2, 3, 4]) # Convert the list into NumPy array for vectorized ops
b = np.array([1, 0, 0]) # Convert the list into NumPy array for vectorized ops
projection = (np.dot(a, b) / np.dot(b, b)) * b # Compute the projection of a onto b
print("Projection of a onto b:", projection)

Projection of a onto b: [2. 0. 0.]


In [16]:
# Example 10: Angle Between Two Vectors
a = np.array([1, 0, 0]) # Convert the list into NumPy array for vectorized ops
b = np.array([0, 1, 0]) # Convert the list into NumPy array for vectorized ops
cos_theta = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)) # Compute the cosine of the angle θ between two vectors a & b
angle_radians = np.arccos(cos_theta) # Compute the inverse cosine
angle_degrees = np.degrees(angle_radians) # Converts an angle from radians to degrees
print("Angle Between Vectors (Degrees):", angle_degrees)

Angle Between Vectors (Degrees): 90.0


In [17]:
# Example 11: Distance Between Two Points
a = np.array([1, 2, 3]) # Convert the list into NumPy array for vectorized ops
b = np.array([4, 5, 6]) # Convert the list into NumPy array for vectorized ops
distance = np.linalg.norm(a - b) # Compute the magnitude (Euclidean Nrom) between two vectors a & b
print("Distance Between Points:", distance)

Distance Between Points: 5.196152422706632


In [18]:
# Matrix Operations
# 1. Matrix Addition
A = np.array([[1, 2], [3, 4]]) # Convert the list into NumPy array for vectorized ops
B = np.array([[5, 6], [7, 8]]) # Convert the list into NumPy array for vectorized ops
addition_result = A + B
print("Matrix Addition:\n", addition_result)

Matrix Addition:
 [[ 6  8]
 [10 12]]


In [19]:
# 2. Matrix Subtraction
subtraction_result = A - B
print("Matrix Subtraction:\n", subtraction_result)

Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]


In [20]:
# 3. Scalar Multiplication
scalar = 3
scalar_multiplication_result = scalar * A
print("Scalar Multiplication:\n", scalar_multiplication_result)

Scalar Multiplication:
 [[ 3  6]
 [ 9 12]]


In [21]:
# 4. Matrix Multiplication (Dot Product)
C = np.array([[2, 3], [4, 5]]) # Convert the list into NumPy array for vectorized ops
D = np.array([[1, 2], [3, 4]]) # Convert the list into NumPy array for vectorized ops
matrix_multiplication_result = np.dot(C, D) # Compute the dot product of two arrays a & b
print("Matrix Multiplication (Dot Product):\n", matrix_multiplication_result)

Matrix Multiplication (Dot Product):
 [[11 16]
 [19 28]]


In [22]:
# 5. Element-wise Multiplication
elementwise_multiplication_result = A * B
print("Element-wise Multiplication:\n", elementwise_multiplication_result)

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]


In [23]:
# 6. Matrix Transposition
transpose_result = A.T # Transpose the matrix A
print("Matrix Transposition:\n", transpose_result)

Matrix Transposition:
 [[1 3]
 [2 4]]


In [24]:
# 7. Matrix Determinant Calculation
E = np.array([[4, 7], [2, 6]]) # Convert the list into NumPy array for vectorized ops
determinant_result = np.linalg.det(E) # Compute the determinant of a square matrix E
print("Matrix Determinant:\n", determinant_result)

Matrix Determinant:
 10.000000000000002


In [25]:
# 8. Matrix Inversion
inverse_result = np.linalg.inv(E) # Compute the inverse of a square matrix E
print("Matrix Inversion:\n", inverse_result)

Matrix Inversion:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [26]:
# 9. Matrix Rank Calculation
F = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # Convert the list into NumPy array for vectorized ops
rank_result = np.linalg.matrix_rank(F) # Compute the rank of a matrix F
print("Matrix Rank:\n", rank_result)

Matrix Rank:
 2


In [27]:
# 10. Eigenvalues and Eigenvectors Calculation
G = np.array([[4, -2], [1, 1]]) # Convert the list into NumPy array for vectorized ops
eigenvalues, eigenvectors = np.linalg.eig(G) # Compute the eigenvalues and eigenvectors of a square matrix G
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [28]:
# 1. Tensor Addition
A = np.array([[1, 2], [3, 4]]) # Convert the list into NumPy array for vectorized ops
B = np.array([[5, 6], [7, 8]]) # Convert the list into NumPy array for vectorized ops
addition_result = A + B
print("Tensor Addition:\n", addition_result)

Tensor Addition:
 [[ 6  8]
 [10 12]]


In [29]:
# 2. Tensor Subtraction
subtraction_result = A - B
print("Tensor Subtraction:\n", subtraction_result)

Tensor Subtraction:
 [[-4 -4]
 [-4 -4]]


In [30]:
# 3. Scalar Multiplication
scalar = 3
scalar_multiplication_result = scalar * A
print("Scalar Multiplication:\n", scalar_multiplication_result)

Scalar Multiplication:
 [[ 3  6]
 [ 9 12]]


In [31]:
# 4. Tensor Multiplication (Dot Product)
C = np.array([[2, 3], [4, 5]]) # Convert the list into NumPy array for vectorized ops
D = np.array([[1, 2], [3, 4]]) # Convert the list into NumPy array for vectorized ops
dot_product_result = np.dot(C, D) # Compute the dot product of two arrays a & b
print("Tensor Multiplication (Dot Product):\n", dot_product_result)

Tensor Multiplication (Dot Product):
 [[11 16]
 [19 28]]


In [32]:
# 5. Element-wise Multiplication
elementwise_multiplication_result = A * B
print("Element-wise Multiplication:\n", elementwise_multiplication_result)

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]


In [33]:
# 6. Tensor Transposition
T = np.array([[1, 2, 3], [4, 5, 6]]) # Convert the list into NumPy array for vectorized ops
transpose_result = T.T # Transpose the matrix T
print("Tensor Transposition:\n", transpose_result)

Tensor Transposition:
 [[1 4]
 [2 5]
 [3 6]]


In [34]:
T_3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # Convert the list into NumPy array for vectorized ops
summed_result = np.sum(T_3D, axis=0) # Compute the sum of elements in a multi-dimensional array along a specified axis
print("Tensor Contraction (Summation over Axes):\n", summed_result)

Tensor Contraction (Summation over Axes):
 [[ 6  8]
 [10 12]]


In [35]:
from sympy import symbols, expand
from scipy.integrate import quad

In [36]:
# Vector Spaces
# 1. Real Vector Space (ℝ) Operations
def real_vector_space():
    v1 = np.array([2, 3])  # Define first vector
    v2 = np.array([4, -1]) # Define second vector
    addition = v1 + v2  # Vector addition
    scalar_mult = 2 * v1  # Scalar multiplication
    return addition, scalar_mult

# 2. Complex Vector Space (ℂ) Operations
def complex_vector_space():
    w1 = np.array([1 + 1j, 2 - 1j])  # Define first complex vector
    w2 = np.array([3 - 2j, -1 + 1j]) # Define second complex vector
    addition = w1 + w2  # Complex vector addition
    scalar_mult = (2 + 1j) * w1  # Scalar multiplication with a complex number
    return addition, scalar_mult

# 3. Euclidean Space (ℝⁿ) Operations
def euclidean_space():
    x = np.array([1, 2, 3])  # First vector in Euclidean space
    y = np.array([4, 5, 6])  # Second vector in Euclidean space
    dot_product = np.dot(x, y)  # Compute dot product
    return dot_product

# 4. Function Space (Integrating functions)
def function_space():
    f = lambda x: x**2  # Define first function f(x) = x²
    g = lambda x: 2*x  # Define second function g(x) = 2x
    f_plus_g = lambda x: f(x) + g(x)  # Function addition (f + g)
    integral_f, _ = quad(f, 0, 1)  # Integrate f(x) from 0 to 1
    integral_f_plus_g, _ = quad(f_plus_g, 0, 1)  # Integrate (f + g) from 0 to 1
    return integral_f, integral_f_plus_g

# 5. Polynomial Vector Space
def polynomial_vector_space():
    x = symbols('x')  # Define a symbolic variable x
    p = x**2 + 2*x + 3  # Define first polynomial
    q = 4*x**2 - x + 5  # Define second polynomial
    addition = expand(p + q)  # Polynomial addition
    scalar_mult = expand(-2 * p)  # Scalar multiplication by -2
    return addition, scalar_mult

# 6. Matrix Vector Space
def matrix_vector_space():
    A = np.array([[1, 2], [3, 4]])  # Define first matrix
    B = np.array([[5, 6], [7, 8]])  # Define second matrix
    addition = A + B  # Matrix addition
    scalar_mult = 2 * A  # Scalar multiplication
    return addition, scalar_mult

# 7. Normed Vector Space
def normed_vector_space():
    v = np.array([3, 4, 12])  # Define a vector
    norm = np.linalg.norm(v)  # Compute Euclidean norm (magnitude)
    return norm

# Running all functions and printing results
if __name__ == "__main__":
    print("Real Vector Space:", real_vector_space())
    print("Complex Vector Space:", complex_vector_space())
    print("Euclidean Space:", euclidean_space())
    print("Function Space:", function_space())
    print("Polynomial Vector Space:", polynomial_vector_space())
    print("Matrix Vector Space:", matrix_vector_space())
    print("Normed Vector Space:", normed_vector_space())

Real Vector Space: (array([6, 2]), array([4, 6]))
Complex Vector Space: (array([4.-1.j, 1.+0.j]), array([1.+3.j, 5.+0.j]))
Euclidean Space: 32
Function Space: (0.33333333333333337, 1.3333333333333333)
Polynomial Vector Space: (5*x**2 + x + 8, -2*x**2 - 4*x - 6)
Matrix Vector Space: (array([[ 6,  8],
       [10, 12]]), array([[2, 4],
       [6, 8]]))
Normed Vector Space: 13.0


In [37]:
from sympy import Matrix

In [38]:
#Linear Combination & Span
# 1. Basic Linear Combination
# Computes a linear combination of two vectors with given scalar coefficients.
def basic_linear_combination():
    v1 = np.array([2, 3])  # First vector
    v2 = np.array([-1, 4])  # Second vector
    a, b = 3, -2  # Scalars
    result = a * v1 + b * v2  # Linear combination formula
    return result

# 2. Checking if a Vector is in the Span
# Determines whether a vector can be expressed as a linear combination of given vectors.
def is_vector_in_span():
    A = np.array([[1, 3], [2, 4]])  # Matrix formed by spanning vectors
    b = np.array([5, 6])  # Target vector to check
    try:
        solution = np.linalg.solve(A, b)  # Solves Ax = b for x
        return True, solution  # If successful, vector is in span
    except np.linalg.LinAlgError:
        return False, None  # If no solution, vector is not in span

# 3. Span of Two Vectors
# Checks whether two vectors span R^2 by computing matrix rank.
def span_of_two_vectors():
    v1 = np.array([1, 2])  # First vector
    v2 = np.array([3, 5])  # Second vector
    span = np.column_stack((v1, v2))  # Form matrix with vectors as columns
    rank = np.linalg.matrix_rank(span)  # Compute rank of matrix
    return rank == 2  # If rank is 2, they span R^2

# 4. Span of a Set of Vectors
# Checks whether a given set of vectors spans R^3.
def span_of_set_of_vectors():
    V = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])  # Standard basis vectors in R^3
    rank = np.linalg.matrix_rank(V)  # Compute rank of matrix
    return rank == 3  # If rank is 3, they span R^3

# 5. Basis and Dimension of a Span
# Finds the basis and dimension of the span of a given set of vectors.
def basis_and_dimension_of_span():
    vectors = Matrix([[1, 2, 3], [2, 4, 6], [3, 1, 4]])  # Given set of vectors
    reduced, pivots = vectors.rref()  # Compute reduced row echelon form (RREF)
    basis_vectors = [vectors[:, i] for i in pivots]  # Extract basis vectors
    dimension = len(basis_vectors)  # Count number of basis vectors
    return basis_vectors, dimension

# Running the functions
if __name__ == "__main__":
    print("Basic Linear Combination:", basic_linear_combination())
    print("Is Vector in Span:", is_vector_in_span())
    print("Span of Two Vectors:", span_of_two_vectors())
    print("Span of Set of Vectors:", span_of_set_of_vectors())
    print("Basis and Dimension of Span:", basis_and_dimension_of_span())

Basic Linear Combination: [8 1]
Is Vector in Span: (True, array([-1.,  2.]))
Span of Two Vectors: True
Span of Set of Vectors: True
Basis and Dimension of Span: ([Matrix([
[1],
[2],
[3]]), Matrix([
[2],
[4],
[1]])], 2)


In [39]:
# Linear Transformations
def scaling_transformation(vector, scalar):
    """
    Scales a vector by a given scalar.
    Multiplying each component of the vector by the scalar.
    """
    return scalar * vector

def rotation_transformation(vector, angle):
    """
    Rotates a 2D vector by the given angle in degrees.
    Uses a 2x2 rotation matrix to transform the vector.
    """
    theta = np.radians(angle)  # Convert degrees to radians
    rotation_matrix = np.array([[np.cos(theta), -np.sin(theta)], 
                                [np.sin(theta), np.cos(theta)]])
    return rotation_matrix @ vector  # Matrix-vector multiplication

def reflection_transformation(vector):
    """
    Reflects a 2D vector across the x-axis.
    This negates the y-component while keeping x the same.
    """
    reflection_matrix = np.array([[1, 0], [0, -1]])
    return reflection_matrix @ vector

def shear_transformation(vector, shear_factor):
    """
    Applies a horizontal shear transformation.
    The x-component is modified based on the y-component.
    """
    shear_matrix = np.array([[1, shear_factor], [0, 1]])
    return shear_matrix @ vector

def projection_transformation(vector, onto_vector):
    """
    Projects one vector onto another vector.
    Uses the dot product formula to calculate the projection.
    """
    dot_product = np.dot(vector, onto_vector)  # Compute dot product
    norm_squared = np.dot(onto_vector, onto_vector)  # Compute squared norm of onto_vector
    return (dot_product / norm_squared) * onto_vector  # Compute the projection result

def identity_transformation(vector):
    """
    Applies the identity transformation (returns the vector unchanged).
    Uses an identity matrix that does not alter the input vector.
    """
    identity_matrix = np.eye(len(vector))  # Generate an identity matrix of appropriate size
    return identity_matrix @ vector

# Example usage
vector = np.array([3, 4])
scalar = 2
shear_factor = 1.5
onto_vector = np.array([1, 2])

# Display results of each transformation
print("Scaling:", scaling_transformation(vector, scalar))
print("Rotation (90 degrees):", rotation_transformation(vector, 90))
print("Reflection across x-axis:", reflection_transformation(vector))
print("Shear transformation:", shear_transformation(vector, shear_factor))
print("Projection onto another vector:", projection_transformation(vector, onto_vector))
print("Identity transformation:", identity_transformation(vector))

Scaling: [6 8]
Rotation (90 degrees): [-4.  3.]
Reflection across x-axis: [ 3 -4]
Shear transformation: [9. 4.]
Projection onto another vector: [2.2 4.4]
Identity transformation: [3. 4.]


In [40]:
# Dot Product and Cross Product
# 1. Two-Dimensional Vectors Dot Product
# Computes the dot product of two 2D vectors.
a = np.array([3, 4])
b = np.array([2, -1])
dot_2d = np.dot(a, b)
print("Dot Product (2D):", dot_2d)

Dot Product (2D): 2


In [41]:
# 2. Three-Dimensional Vectors Dot Product
# Computes the dot product of two 3D vectors.
a = np.array([1, 2, 3])
b = np.array([-2, 0, 4])
dot_3d = np.dot(a, b)
print("Dot Product (3D):", dot_3d)

Dot Product (3D): 10


In [42]:
# 3. Projection of a vector onto another
# Formula: projection = (a . b / ||b||^2) * b
b_norm_sq = np.dot(b, b)  # Computes the squared norm of b
projection = (np.dot(a, b) / b_norm_sq) * b  # Computes projection of a onto b
print("Projection of a onto b:", projection)

Projection of a onto b: [-1.  0.  2.]


In [43]:
# 4. Angle Between Two Vectors Using Dot Product
# Formula: cos(theta) = (a . b) / (||a|| * ||b||)
a = np.array([2, 3])
b = np.array([4, -1])
cos_theta = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
print("Cosine of angle:", cos_theta)

Cosine of angle: 0.33633639699815626


In [44]:
# 5. Work Done by a Force
# Work done = Force . Displacement (dot product)
a = np.array([10, 5])  # Force vector
b = np.array([4, 2])   # Displacement vector
work_done = np.dot(a, b)
print("Work Done:", work_done)

Work Done: 50


In [45]:
# 6. Three-Dimensional Vectors Cross Product
# Computes the cross product of two 3D vectors.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
cross_3d = np.cross(a, b)
print("Cross Product (3D):", cross_3d)

Cross Product (3D): [-3  6 -3]


In [46]:
# 7. Geometric Interpretation of Cross Product (Area of Parallelogram)
# The magnitude of the cross product gives the area of the parallelogram formed by two vectors.
area = np.linalg.norm(cross_3d)
print("Area of parallelogram:", area)

Area of parallelogram: 7.3484692283495345


In [47]:
# 8. Torque Calculation Using Cross Product
# Torque = r x F (cross product of position vector and force vector)
r = np.array([2, 3, 4])  # Position vector
F = np.array([5, 6, 7])  # Force vector
torque = np.cross(r, F)
print("Torque:", torque)

Torque: [-3  6 -3]


In [48]:
# 9. Perpendicular Vectors and Cross Product
# Computes the cross product of two perpendicular vectors in 3D.
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
cross_perp = np.cross(a, b)
print("Cross Product of Perpendicular Vectors:", cross_perp)

Cross Product of Perpendicular Vectors: [0 0 1]


In [49]:
# 10. Unit Vector Normal to Two Vectors
# Computes the unit normal vector to the plane formed by two vectors.
unit_normal = cross_3d / np.linalg.norm(cross_3d)  # Normalizing the cross product
print("Unit Normal Vector:", unit_normal)

Unit Normal Vector: [-0.40824829  0.81649658 -0.40824829]


In [50]:
from scipy.spatial.distance import mahalanobis
from numpy.linalg import inv, norm

In [51]:
# Function to compute L1 Norm (Manhattan Distance)
def l1_norm(a, b):
    return np.sum(np.abs(a - b))

# Function to compute L2 Norm (Euclidean Distance)
def l2_norm(a, b):
    return np.sqrt(np.sum((a - b) ** 2))

# Function to compute Lp Norm (Generalized Minkowski Distance)
def lp_norm(a, b, p):
    return np.power(np.sum(np.abs(a - b) ** p), 1 / p)

# Function to compute Max Norm (Chebyshev Distance)
def max_norm(a, b):
    return np.max(np.abs(a - b))

# Function to compute Frobenius Norm for matrices (used in matrix analysis)
def frobenius_norm(matrix):
    return np.sqrt(np.sum(matrix ** 2))

# Function to compute Cosine Similarity (measures angle similarity between vectors)
def cosine_similarity(a, b):
    return np.dot(a, b) / (norm(a) * norm(b))

# Function to compute Mahalanobis Distance (distance metric accounting for correlations in data)
def mahalanobis_distance(x, mean, cov):
    inv_cov = inv(cov)  # Compute the inverse of the covariance matrix
    diff = x - mean  # Compute the difference vector
    return np.sqrt(np.dot(np.dot(diff.T, inv_cov), diff))

# Define example vectors and matrix
a = np.array([3, -4, 7])  # Example vector a
b = np.array([1, 2, 5])   # Example vector b
A = np.array([[1, -2, 3], [4, 5, -6]])  # Example matrix

# Example input for Mahalanobis Distance calculation
x = np.array([3, 5])  # Example data point
mu = np.array([2, 4])  # Mean vector
cov_matrix = np.array([[1, 0.5], [0.5, 1]])  # Covariance matrix

# Compute and print values for different norm and distance calculations
print("L1 Norm (Manhattan Distance):", l1_norm(a, b))
print("L2 Norm (Euclidean Distance):", l2_norm(a, b))
print("L3 Norm (Minkowski Distance with p=3):", lp_norm(a, b, 3))
print("Max Norm (Chebyshev Distance):", max_norm(a, b))
print("Frobenius Norm (Matrix Norm):", frobenius_norm(A))
print("Cosine Similarity (Vector Angle Similarity):", cosine_similarity(a, b))
print("Mahalanobis Distance (Correlation-Based Distance):", mahalanobis_distance(x, mu, cov_matrix))

L1 Norm (Manhattan Distance): 10
L2 Norm (Euclidean Distance): 6.6332495807108
L3 Norm (Minkowski Distance with p=3): 6.144633651371694
Max Norm (Chebyshev Distance): 6
Frobenius Norm (Matrix Norm): 9.539392014169456
Cosine Similarity (Vector Angle Similarity): 0.6367145399670133
Mahalanobis Distance (Correlation-Based Distance): 1.1547005383792515


In [52]:
#Eigenvalues & Eigenvectors
# Example 1: Basic Eigenvalue and Eigenvector Calculation
A = np.array([[4, 2], [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)  # Compute eigenvalues and eigenvectors
print("Example 1 - Basic Eigenvalues:", eigenvalues)
print("Example 1 - Basic Eigenvectors:\n", eigenvectors)

Example 1 - Basic Eigenvalues: [5. 2.]
Example 1 - Basic Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [53]:
# Example 2: Diagonalization Using Eigenvalues and Eigenvectors
P = eigenvectors  # Eigenvectors matrix (change of basis)
D = np.diag(eigenvalues)  # Diagonal matrix of eigenvalues
P_inv = np.linalg.inv(P)  # Compute inverse of P
reconstructed_A = P @ D @ P_inv  # Verify A = P * D * P^-1
print("Example 2 - Diagonalized Matrix:\n", reconstructed_A)

Example 2 - Diagonalized Matrix:
 [[4. 2.]
 [1. 3.]]


In [54]:
# Example 3: Symmetric Matrix Eigenvalues - Should yield real and orthogonal eigenvectors
B = np.array([[2, -1], [-1, 2]])
eigenvalues_B, eigenvectors_B = np.linalg.eig(B)
print("Example 3 - Symmetric Matrix Eigenvalues:", eigenvalues_B)
print("Example 3 - Symmetric Matrix Eigenvectors:\n", eigenvectors_B)

Example 3 - Symmetric Matrix Eigenvalues: [3. 1.]
Example 3 - Symmetric Matrix Eigenvectors:
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [55]:
# Example 4: Singular Matrix Eigenvalues - One eigenvalue should be zero
C = np.array([[1, 2], [2, 4]])  # Rank-deficient matrix
eigenvalues_C, eigenvectors_C = np.linalg.eig(C)
print("Example 4 - Singular Matrix Eigenvalues:", eigenvalues_C)

Example 4 - Singular Matrix Eigenvalues: [0. 5.]


In [56]:
# Example 5: Eigenvalues in Markov Chains - The largest eigenvalue should be 1 for a stochastic matrix
M = np.array([[0.7, 0.3], [0.4, 0.6]])
eigenvalues_M, eigenvectors_M = np.linalg.eig(M)
print("Example 5 - Markov Chain Eigenvalues:", eigenvalues_M)

Example 5 - Markov Chain Eigenvalues: [1.  0.3]


In [57]:
# Example 6: Eigenvalues and Eigenvectors in PCA - Used in Principal Component Analysis
S = np.array([[2, 1], [1, 2]])  # Covariance-like matrix
eigenvalues_S, eigenvectors_S = np.linalg.eig(S)
print("Example 6 - PCA Eigenvalues:", eigenvalues_S)
print("Example 6 - PCA Eigenvectors:\n", eigenvectors_S)

Example 6 - PCA Eigenvalues: [3. 1.]
Example 6 - PCA Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [58]:
import scipy.linalg

In [ ]:
# Matrix Decomposition
# Example 1: LU Decomposition (General Square Matrix)
A1 = np.array([[4, 3], [6, 3]])
P1, L1, U1 = scipy.linalg.lu(A1)
lu_result_1 = {"P": P1, "L": L1, "U": U1}
print(lu_result_1)

{'P': array([[0., 1.],
       [1., 0.]]), 'L': array([[1.        , 0.        ],
       [0.66666667, 1.        ]]), 'U': array([[6., 3.],
       [0., 1.]])}


In [61]:
# Example 2: LU Decomposition with Partial Pivoting
A2 = np.array([[2, 3, 1], [4, 1, 3], [3, 2, 4]])
P2, L2, U2 = scipy.linalg.lu(A2)
lu_result_2 = {"P": P2, "L": L2, "U": U2}
print(lu_result_2)

{'P': array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]]), 'L': array([[1.  , 0.  , 0.  ],
       [0.5 , 1.  , 0.  ],
       [0.75, 0.5 , 1.  ]]), 'U': array([[ 4. ,  1. ,  3. ],
       [ 0. ,  2.5, -0.5],
       [ 0. ,  0. ,  2. ]])}


In [62]:
# Example 3: QR Decomposition for a Full-Rank Square Matrix
A3 = np.array([[1, -1], [1, 1]])
Q3, R3 = np.linalg.qr(A3)
qr_result_3 = {"Q": Q3, "R": R3}
print(qr_result_3)

{'Q': array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]]), 'R': array([[-1.41421356e+00, -3.33066907e-16],
       [ 0.00000000e+00,  1.41421356e+00]])}


In [63]:
# Example 4: QR Decomposition for a Rectangular Matrix
A4 = np.array([[1, 2], [3, 4], [5, 6]])
Q4, R4 = np.linalg.qr(A4)
qr_result_4 = {"Q": Q4, "R": R4}
print(qr_result_4)

{'Q': array([[-0.16903085,  0.89708523],
       [-0.50709255,  0.27602622],
       [-0.84515425, -0.34503278]]), 'R': array([[-5.91607978, -7.43735744],
       [ 0.        ,  0.82807867]])}


In [64]:
# Example 5: Singular Value Decomposition (SVD) for a Square Matrix
A5 = np.array([[1, 2], [2, 3]])
U5, S5, Vt5 = np.linalg.svd(A5)
svd_result_5 = {"U": U5, "S": S5, "Vt": Vt5}
print(svd_result_5)

{'U': array([[-0.52573111, -0.85065081],
       [-0.85065081,  0.52573111]]), 'S': array([4.23606798, 0.23606798]), 'Vt': array([[-0.52573111, -0.85065081],
       [ 0.85065081, -0.52573111]])}


In [65]:
# Example 6: Singular Value Decomposition (SVD) for a Rectangular Matrix
A6 = np.array([[1, 2, 3], [4, 5, 6]])
U6, S6, Vt6 = np.linalg.svd(A6)
svd_result_6 = {"U": U6, "S": S6, "Vt": Vt6}
print(svd_result_6)

{'U': array([[-0.3863177 , -0.92236578],
       [-0.92236578,  0.3863177 ]]), 'S': array([9.508032  , 0.77286964]), 'Vt': array([[-0.42866713, -0.56630692, -0.7039467 ],
       [ 0.80596391,  0.11238241, -0.58119908],
       [ 0.40824829, -0.81649658,  0.40824829]])}
