In [2]:
import numpy as np

In [3]:
# Scalar Operations
# Example 1: Scalar Addition
scalar_a = 5
scalar_b = 3
scalar_addition = scalar_a +scalar_b
print("Scalar Addition:", scalar_addition)

Scalar Addition: 8


In [4]:
# Example 2: Scalar Subtraction
scalar_subtraction = scalar_a - scalar_b
print("Scalar Subtraction:", scalar_subtraction)

Scalar Subtraction: 2


In [5]:
# Example 3: Scalar Multiplication
scalar_multiplication = scalar_a * scalar_b
print("Scalar Multiplication:", scalar_multiplication)

Scalar Multiplication: 15


In [6]:
# Example 4: Scalar Division
scalar_division = scalar_a / scalar_b  # Ensure b is not zero
print("Scalar Division:", scalar_division)

Scalar Division: 1.6666666666666667


In [7]:
# Example 5: Scalar Exponentiation
scalar_exponentiation = scalar_a ** scalar_b
print("Scalar Exponentiation:", scalar_exponentiation)

Scalar Exponentiation: 125


In [8]:
# Vector Operations using NumPy
# Example 1: Vector Addition
a = np.array([3, -2, 5]) # Convert the list into NumPy array for vectorized ops
b = np.array([4, 7, -1]) # Convert the list into Numpy array for vectorized ops
vector_addition = a + b
print("Vector Addition:", vector_addition)

Vector Addition: [7 5 4]


In [9]:
# Example 2: Vector Subtraction
a = np.array([6, -3, 2]) # Convert the list into NumPy array for vectorized ops
b = np.array([1, 4, -5]) # Convert the list into NumPy array for vectorized ops
vector_subtraction = a - b
print("Vector Subtraction:", vector_subtraction)

Vector Subtraction: [ 5 -7  7]


In [10]:
# Example 3: Scalar Multiplication
scalar = 3
a = np.array([-2, 5, 4]) # Convert the list into NumPy array for vectorized ops
scalar_multiplication_vector = scalar * a
print("Scalar Multiplication with a Vector:", scalar_multiplication_vector)

Scalar Multiplication with a Vector: [-6 15 12]


In [11]:
# Example 4: Element-wise Vector Multiplication
a = np.array([2, -1, 3]) # Convert the list into NumPy array for vectorized ops
b = np.array([4, 5, -2]) # Convert the list into NumPy array for vectorized ops
elementwise_multiplication = a * b
print("Element-wise Vector Multiplication:", elementwise_multiplication)

Element-wise Vector Multiplication: [ 8 -5 -6]


In [12]:
# Example 5: Dot Product
a = np.array([1, 2, 3]) # Convert the list into NumPy array for vectorized ops
b = np.array([4, -5, 6]) # Convert the list into NumPy array for vectorized ops
dot_product = np.dot(a, b) # Compute dot product on of two vectors a & b
print("Dot Product:", dot_product)

Dot Product: 12


In [13]:
# Example 6: Cross Product
a = np.array([1, 2, 3]) # Convert the list into NumPy array for vectorized ops
b = np.array([4, 5, 6]) # Convert the list into NumPy array for vectorized ops
cross_product = np.cross(a, b) # Compute cross product of two vectors a & b
print("Cross Product:", cross_product)

Cross Product: [-3  6 -3]


In [14]:
# Example 7: Magnitude (Norm) of a Vector
a = np.array([3, 4, 5]) # Convert the list into NumPy array for vectorized ops
magnitude = np.linalg.norm(a) # Compute the magnitude/length of a vector a
print("Magnitude of Vector:", magnitude)

Magnitude of Vector: 7.0710678118654755


In [15]:
# Example 8: Unit Vector Calculation
a = np.array([3, 4, 5]) # Convert the list into NumPy array for vectorized ops
unit_vector = a / np.linalg.norm(a) # Compute the unit vector of a given the length of a vector a
print("Unit Vector:", unit_vector)

Unit Vector: [0.42426407 0.56568542 0.70710678]


In [16]:
# Example 9: Projection of One Vector onto Another
a = np.array([2, 3, 4]) # Convert the list into NumPy array for vectorized ops
b = np.array([1, 0, 0]) # Convert the list into NumPy array for vectorized ops
projection = (np.dot(a, b) / np.dot(b, b)) * b # Compute the projection of a onto b
print("Projection of a onto b:", projection)

Projection of a onto b: [2. 0. 0.]


In [17]:
# Example 10: Angle Between Two Vectors
a = np.array([1, 0, 0]) # Convert the list into NumPy array for vectorized ops
b = np.array([0, 1, 0]) # Convert the list into NumPy array for vectorized ops
cos_theta = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)) # Compute the cosine of the angle θ between two vectors a & b
angle_radians = np.arccos(cos_theta) # Compute the inverse cosine
angle_degrees = np.degrees(angle_radians) # Converts an angle from radians to degrees
print("Angle Between Vectors (Degrees):", angle_degrees)

Angle Between Vectors (Degrees): 90.0


In [18]:
# Example 11: Distance Between Two Points
a = np.array([1, 2, 3]) # Convert the list into NumPy array for vectorized ops
b = np.array([4, 5, 6]) # Convert the list into NumPy array for vectorized ops
distance = np.linalg.norm(a - b) # Compute the magnitude (Euclidean Nrom) between two vectors a & b
print("Distance Between Points:", distance)

Distance Between Points: 5.196152422706632


In [19]:
# Matrix Operations
# 1. Matrix Addition
A = np.array([[1, 2], [3, 4]]) # Convert the list into NumPy array for vectorized ops
B = np.array([[5, 6], [7, 8]]) # Convert the list into NumPy array for vectorized ops
addition_result = A + B
print("Matrix Addition:\n", addition_result)

Matrix Addition:
 [[ 6  8]
 [10 12]]


In [20]:
# 2. Matrix Subtraction
subtraction_result = A - B
print("Matrix Subtraction:\n", subtraction_result)

Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]


In [21]:
# 3. Scalar Multiplication
scalar = 3
scalar_multiplication_result = scalar * A
print("Scalar Multiplication:\n", scalar_multiplication_result)

Scalar Multiplication:
 [[ 3  6]
 [ 9 12]]


In [22]:
# 4. Matrix Multiplication (Dot Product)
C = np.array([[2, 3], [4, 5]]) # Convert the list into NumPy array for vectorized ops
D = np.array([[1, 2], [3, 4]]) # Convert the list into NumPy array for vectorized ops
matrix_multiplication_result = np.dot(C, D) # Compute the dot product of two arrays a & b
print("Matrix Multiplication (Dot Product):\n", matrix_multiplication_result)

Matrix Multiplication (Dot Product):
 [[11 16]
 [19 28]]


In [23]:
# 5. Element-wise Multiplication
elementwise_multiplication_result = A * B
print("Element-wise Multiplication:\n", elementwise_multiplication_result)

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]


In [24]:
# 6. Matrix Transposition
transpose_result = A.T # Transpose the matrix A
print("Matrix Transposition:\n", transpose_result)

Matrix Transposition:
 [[1 3]
 [2 4]]


In [25]:
# 7. Matrix Determinant Calculation
E = np.array([[4, 7], [2, 6]]) # Convert the list into NumPy array for vectorized ops
determinant_result = np.linalg.det(E) # Compute the determinant of a square matrix E
print("Matrix Determinant:\n", determinant_result)

Matrix Determinant:
 10.000000000000002


In [26]:
# 8. Matrix Inversion
inverse_result = np.linalg.inv(E) # Compute the inverse of a square matrix E
print("Matrix Inversion:\n", inverse_result)

Matrix Inversion:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [27]:
# 9. Matrix Rank Calculation
F = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # Convert the list into NumPy array for vectorized ops
rank_result = np.linalg.matrix_rank(F) # Compute the rank of a matrix F
print("Matrix Rank:\n", rank_result)

Matrix Rank:
 2


In [28]:
# 10. Eigenvalues and Eigenvectors Calculation
G = np.array([[4, -2], [1, 1]]) # Convert the list into NumPy array for vectorized ops
eigenvalues, eigenvectors = np.linalg.eig(G) # Compute the eigenvalues and eigenvectors of a square matrix G
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [29]:
# 1. Tensor Addition
A = np.array([[1, 2], [3, 4]]) # Convert the list into NumPy array for vectorized ops
B = np.array([[5, 6], [7, 8]]) # Convert the list into NumPy array for vectorized ops
addition_result = A + B
print("Tensor Addition:\n", addition_result)

Tensor Addition:
 [[ 6  8]
 [10 12]]


In [30]:
# 2. Tensor Subtraction
subtraction_result = A - B
print("Tensor Subtraction:\n", subtraction_result)

Tensor Subtraction:
 [[-4 -4]
 [-4 -4]]


In [31]:
# 3. Scalar Multiplication
scalar = 3
scalar_multiplication_result = scalar * A
print("Scalar Multiplication:\n", scalar_multiplication_result)

Scalar Multiplication:
 [[ 3  6]
 [ 9 12]]


In [32]:
# 4. Tensor Multiplication (Dot Product)
C = np.array([[2, 3], [4, 5]]) # Convert the list into NumPy array for vectorized ops
D = np.array([[1, 2], [3, 4]]) # Convert the list into NumPy array for vectorized ops
dot_product_result = np.dot(C, D) # Compute the dot product of two arrays a & b
print("Tensor Multiplication (Dot Product):\n", dot_product_result)

Tensor Multiplication (Dot Product):
 [[11 16]
 [19 28]]


In [33]:
# 5. Element-wise Multiplication
elementwise_multiplication_result = A * B
print("Element-wise Multiplication:\n", elementwise_multiplication_result)

Element-wise Multiplication:
 [[ 5 12]
 [21 32]]


In [34]:
# 6. Tensor Transposition
T = np.array([[1, 2, 3], [4, 5, 6]]) # Convert the list into NumPy array for vectorized ops
transpose_result = T.T # Transpose the matrix T
print("Tensor Transposition:\n", transpose_result)

Tensor Transposition:
 [[1 4]
 [2 5]
 [3 6]]


In [35]:
T_3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # Convert the list into NumPy array for vectorized ops
summed_result = np.sum(T_3D, axis=0) # Compute the sum of elements in a multi-dimensional array along a specified axis
print("Tensor Contraction (Summation over Axes):\n", summed_result)

Tensor Contraction (Summation over Axes):
 [[ 6  8]
 [10 12]]


In [36]:
from sympy import symbols, expand
from scipy.integrate import quad

In [37]:
# Vector Spaces
# 1. Real Vector Space (ℝ) Operations
def real_vector_space():
    v1 = np.array([2, 3])  # Define first vector
    v2 = np.array([4, -1]) # Define second vector
    addition = v1 + v2  # Vector addition
    scalar_mult = 2 * v1  # Scalar multiplication
    return addition, scalar_mult

# 2. Complex Vector Space (ℂ) Operations
def complex_vector_space():
    w1 = np.array([1 + 1j, 2 - 1j])  # Define first complex vector
    w2 = np.array([3 - 2j, -1 + 1j]) # Define second complex vector
    addition = w1 + w2  # Complex vector addition
    scalar_mult = (2 + 1j) * w1  # Scalar multiplication with a complex number
    return addition, scalar_mult

# 3. Euclidean Space (ℝⁿ) Operations
def euclidean_space():
    x = np.array([1, 2, 3])  # First vector in Euclidean space
    y = np.array([4, 5, 6])  # Second vector in Euclidean space
    dot_product = np.dot(x, y)  # Compute dot product
    return dot_product

# 4. Function Space (Integrating functions)
def function_space():
    f = lambda x: x**2  # Define first function f(x) = x²
    g = lambda x: 2*x  # Define second function g(x) = 2x
    f_plus_g = lambda x: f(x) + g(x)  # Function addition (f + g)
    integral_f, _ = quad(f, 0, 1)  # Integrate f(x) from 0 to 1
    integral_f_plus_g, _ = quad(f_plus_g, 0, 1)  # Integrate (f + g) from 0 to 1
    return integral_f, integral_f_plus_g

# 5. Polynomial Vector Space
def polynomial_vector_space():
    x = symbols('x')  # Define a symbolic variable x
    p = x**2 + 2*x + 3  # Define first polynomial
    q = 4*x**2 - x + 5  # Define second polynomial
    addition = expand(p + q)  # Polynomial addition
    scalar_mult = expand(-2 * p)  # Scalar multiplication by -2
    return addition, scalar_mult

# 6. Matrix Vector Space
def matrix_vector_space():
    A = np.array([[1, 2], [3, 4]])  # Define first matrix
    B = np.array([[5, 6], [7, 8]])  # Define second matrix
    addition = A + B  # Matrix addition
    scalar_mult = 2 * A  # Scalar multiplication
    return addition, scalar_mult

# 7. Normed Vector Space
def normed_vector_space():
    v = np.array([3, 4, 12])  # Define a vector
    norm = np.linalg.norm(v)  # Compute Euclidean norm (magnitude)
    return norm

# Running all functions and printing results
if __name__ == "__main__":
    print("Real Vector Space:", real_vector_space())
    print("Complex Vector Space:", complex_vector_space())
    print("Euclidean Space:", euclidean_space())
    print("Function Space:", function_space())
    print("Polynomial Vector Space:", polynomial_vector_space())
    print("Matrix Vector Space:", matrix_vector_space())
    print("Normed Vector Space:", normed_vector_space())

Real Vector Space: (array([6, 2]), array([4, 6]))
Complex Vector Space: (array([4.-1.j, 1.+0.j]), array([1.+3.j, 5.+0.j]))
Euclidean Space: 32
Function Space: (0.33333333333333337, 1.3333333333333333)
Polynomial Vector Space: (5*x**2 + x + 8, -2*x**2 - 4*x - 6)
Matrix Vector Space: (array([[ 6,  8],
       [10, 12]]), array([[2, 4],
       [6, 8]]))
Normed Vector Space: 13.0


In [38]:
from sympy import Matrix

In [39]:
#Linear Combination & Span
# 1. Basic Linear Combination
# Computes a linear combination of two vectors with given scalar coefficients.
def basic_linear_combination():
    v1 = np.array([2, 3])  # First vector
    v2 = np.array([-1, 4])  # Second vector
    a, b = 3, -2  # Scalars
    result = a * v1 + b * v2  # Linear combination formula
    return result

# 2. Checking if a Vector is in the Span
# Determines whether a vector can be expressed as a linear combination of given vectors.
def is_vector_in_span():
    A = np.array([[1, 3], [2, 4]])  # Matrix formed by spanning vectors
    b = np.array([5, 6])  # Target vector to check
    try:
        solution = np.linalg.solve(A, b)  # Solves Ax = b for x
        return True, solution  # If successful, vector is in span
    except np.linalg.LinAlgError:
        return False, None  # If no solution, vector is not in span

# 3. Span of Two Vectors
# Checks whether two vectors span R^2 by computing matrix rank.
def span_of_two_vectors():
    v1 = np.array([1, 2])  # First vector
    v2 = np.array([3, 5])  # Second vector
    span = np.column_stack((v1, v2))  # Form matrix with vectors as columns
    rank = np.linalg.matrix_rank(span)  # Compute rank of matrix
    return rank == 2  # If rank is 2, they span R^2

# 4. Span of a Set of Vectors
# Checks whether a given set of vectors spans R^3.
def span_of_set_of_vectors():
    V = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])  # Standard basis vectors in R^3
    rank = np.linalg.matrix_rank(V)  # Compute rank of matrix
    return rank == 3  # If rank is 3, they span R^3

# 5. Basis and Dimension of a Span
# Finds the basis and dimension of the span of a given set of vectors.
def basis_and_dimension_of_span():
    vectors = Matrix([[1, 2, 3], [2, 4, 6], [3, 1, 4]])  # Given set of vectors
    reduced, pivots = vectors.rref()  # Compute reduced row echelon form (RREF)
    basis_vectors = [vectors[:, i] for i in pivots]  # Extract basis vectors
    dimension = len(basis_vectors)  # Count number of basis vectors
    return basis_vectors, dimension

# Running the functions
if __name__ == "__main__":
    print("Basic Linear Combination:", basic_linear_combination())
    print("Is Vector in Span:", is_vector_in_span())
    print("Span of Two Vectors:", span_of_two_vectors())
    print("Span of Set of Vectors:", span_of_set_of_vectors())
    print("Basis and Dimension of Span:", basis_and_dimension_of_span())

Basic Linear Combination: [8 1]
Is Vector in Span: (True, array([-1.,  2.]))
Span of Two Vectors: True
Span of Set of Vectors: True
Basis and Dimension of Span: ([Matrix([
[1],
[2],
[3]]), Matrix([
[2],
[4],
[1]])], 2)


In [40]:
# Linear Transformations
def scaling_transformation(vector, scalar):
    """
    Scales a vector by a given scalar.
    Multiplying each component of the vector by the scalar.
    """
    return scalar * vector

def rotation_transformation(vector, angle):
    """
    Rotates a 2D vector by the given angle in degrees.
    Uses a 2x2 rotation matrix to transform the vector.
    """
    theta = np.radians(angle)  # Convert degrees to radians
    rotation_matrix = np.array([[np.cos(theta), -np.sin(theta)], 
                                [np.sin(theta), np.cos(theta)]])
    return rotation_matrix @ vector  # Matrix-vector multiplication

def reflection_transformation(vector):
    """
    Reflects a 2D vector across the x-axis.
    This negates the y-component while keeping x the same.
    """
    reflection_matrix = np.array([[1, 0], [0, -1]])
    return reflection_matrix @ vector

def shear_transformation(vector, shear_factor):
    """
    Applies a horizontal shear transformation.
    The x-component is modified based on the y-component.
    """
    shear_matrix = np.array([[1, shear_factor], [0, 1]])
    return shear_matrix @ vector

def projection_transformation(vector, onto_vector):
    """
    Projects one vector onto another vector.
    Uses the dot product formula to calculate the projection.
    """
    dot_product = np.dot(vector, onto_vector)  # Compute dot product
    norm_squared = np.dot(onto_vector, onto_vector)  # Compute squared norm of onto_vector
    return (dot_product / norm_squared) * onto_vector  # Compute the projection result

def identity_transformation(vector):
    """
    Applies the identity transformation (returns the vector unchanged).
    Uses an identity matrix that does not alter the input vector.
    """
    identity_matrix = np.eye(len(vector))  # Generate an identity matrix of appropriate size
    return identity_matrix @ vector

# Example usage
vector = np.array([3, 4])
scalar = 2
shear_factor = 1.5
onto_vector = np.array([1, 2])

# Display results of each transformation
print("Scaling:", scaling_transformation(vector, scalar))
print("Rotation (90 degrees):", rotation_transformation(vector, 90))
print("Reflection across x-axis:", reflection_transformation(vector))
print("Shear transformation:", shear_transformation(vector, shear_factor))
print("Projection onto another vector:", projection_transformation(vector, onto_vector))
print("Identity transformation:", identity_transformation(vector))

Scaling: [6 8]
Rotation (90 degrees): [-4.  3.]
Reflection across x-axis: [ 3 -4]
Shear transformation: [9. 4.]
Projection onto another vector: [2.2 4.4]
Identity transformation: [3. 4.]
